name: Create Empty Commit on Branch1

on:
  schedule:
    - cron:  '30 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name 'SamVia'
        git config --global user.email 'samuele.vianello2002@gmail.com'

    - name: Debug
      run: |
        echo "Current branch:"
        git branch
        echo "Remote branches:"
        git branch -r

    - name: Create empty commit on christmas-clockino
      run: |
        git checkout christmas-clockino
        git commit --allow-empty -m "Empty commit on christmas-clockino"
        git push origin christmas-clockino
