name: Create Empty Commits

on:
  schedule:
    - cron:  '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config --global user.name 'SamVia'
        git config --global user.email 'samuele.vianello2002@gmail.com'

    - name: Create empty commit on main
      run: |
        git checkout main
        git commit --allow-empty -m "Empty commit on main"
        git push origin main

    - name: Create empty commit on other branch
      run: |
        git checkout christmas-clockino
        git commit --allow-empty -m "Empty commit on christmas-clockino"
        git push origin christmas-clockino
